country_code_to_cities = {"HT":["cap-haitien","carrefour","croix-des-bouquets","delmas 73","desarmes","fond parisien","gonaives","grangwav","gressier","hinche","jacmel","jeremie","kenscoff","lenbe","leogane","les cayes","miragoane","petionville","port-au-prince","port-de-paix","saint-marc","saint-raphael","thomazeau","ti port-de-paix","tigwav","verrettes"],"US":[""New York NY",
"Los Angeles CA",
"Chicago IL",
"Houston TX",
"Phoenix AZ",
"Philadelphia PA",
"San Antonio TX",
"San Diego CA",
"Dallas TX",
"San Jose CA",
"Austin TX",
"Jacksonville FL",
"Fort Worth TX",
"Columbus OH",
"Indianapolis IN",
"Charlotte NC",
"San Francisco CA",
"Seattle WA",
"Denver CO",
"Oklahoma City OK",
"Nashville TN",
"El Paso TX",
"Washington DC",
"Boston MA",
"Las Vegas NV",
"Portland OR",
"Detroit MI",
"Louisville KY",
"Memphis TN",
"Baltimore MD",
"Milwaukee WI",
"Albuquerque NM",
"Fresno CA",
"Tucson AZ",
"Sacramento CA",
"Mesa AZ",
"Kansas City MO",
"Atlanta GA",
"Omaha NE",
"Colorado Springs CO",
"Raleigh NC",
"Virginia Beach VA",
"Long Beach CA",
"Miami FL",
"Oakland CA",
"Minneapolis MN",
"Tulsa OK",
"Bakersfield CA",
"Wichita KS",
"Arlington TX",
"Aurora CO",
"Tampa FL",
"New Orleans LA",
"Cleveland OH",
"Anaheim CA",
"Honolulu HI",
"Henderson NV",
"Stockton CA",
"Lexington KY",
"Corpus Christi TX",
"Riverside CA",
"Santa Ana CA",
"Orlando FL",
"Irvine CA",
"Cincinnati OH",
"Newark NJ",
"St. Paul MN",
"Pittsburgh PA",
"Greensboro NC",
"St. Louis MO",
"Lincoln NE",
"Plano TX",
"Anchorage AK",
"Durham NC",
"Jersey City NJ",
"Chandler AZ",
"Chula Vista CA",
"Buffalo NY",
"North Las Vegas NV",
"Gilbert AZ",
"Madison WI",
"Reno NV",
"Toledo OH",
"Fort Wayne IN",
"Lubbock TX",
"St. Petersburg FL",
"Laredo TX",
"Irving TX",
"Chesapeake VA",
"Winston-Salem NC",
"Glendale AZ",
"Scottsdale AZ",
"Garland TX",
"Boise City ID",
"Norfolk VA",
"Spokane WA",
"Fremont CA",
"Richmond VA",
"Santa Clarita CA",
"San Bernardino CA",
"Baton Rouge LA",
"Hialeah FL",
"Tacoma WA",
"Modesto CA",
"Port St. Lucie FL",
"Huntsville AL",
"Des Moines IA",
"Moreno Valley CA",
"Fontana CA",
"Frisco TX",
"Rochester NY",
"Yonkers NY",
"Fayetteville NC",
"Worcester MA",
"Columbus GA",
"Cape Coral FL",
"McKinney TX",
"Little Rock AR",
"Oxnard CA",
"Amarillo TX",
"Augusta-Richmond County GA",
"Salt Lake City UT",
"Montgomery AL",
"Birmingham AL",
"Grand Rapids MI",
"Grand Prairie TX",
"Overland Park KS",
"Tallahassee FL",
"Huntington Beach CA",
"Sioux Falls SD",
"Peoria AZ",
"Knoxville TN",
"Glendale CA",
"Vancouver WA",
"Providence RI",
"Akron OH",
"Brownsville TX",
"Mobile AL",
"Newport News VA",
"Tempe AZ",
"Shreveport LA",
"Chattanooga TN",
"Fort Lauderdale FL",
"Aurora IL",
"Elk Grove CA",
"Ontario CA",
"Salem OR",
"Cary NC",
"Santa Rosa CA",
"Rancho Cucamonga CA",
"Eugene OR",
"Oceanside CA",
"Clarksville TN",
"Garden Grove CA",
"Lancaster CA",
"Springfield MO",
"Pembroke Pines FL",
"Fort Collins CO",
"Palmdale CA",
"Salinas CA",
"Hayward CA",
"Corona CA",
"Paterson NJ",
"Murfreesboro TN",
"Macon-Bibb County GA",
"Lakewood CO",
"Killeen TX",
"Springfield MA",
"Alexandria VA",
"Kansas City KS",
"Sunnyvale CA",
"Hollywood FL",
"Roseville CA",
"Charleston SC",
"Escondido CA",
"Joliet IL",
"Jackson MS",
"Bellevue WA",
"Surprise AZ",
"Naperville IL",
"Pasadena TX",
"Pomona CA",
"Bridgeport CT",
"Denton TX",
"Rockford IL",
"Mesquite TX",
"Savannah GA",
"Syracuse NY",
"McAllen TX",
"Torrance CA",
"Olathe KS",
"Visalia CA",
"Thornton CO",
"Fullerton CA",
"Gainesville FL",
"Waco TX",
"West Valley City UT",
"Warren MI",
"Hampton VA",
"Dayton OH",
"Columbia SC",
"Orange CA",
"Cedar Rapids IA",
"Stamford CT",
"Victorville CA",
"Pasadena CA",
"Elizabeth NJ",
"New Haven CT",
"Miramar FL",
"Kent WA",
"Sterling Heights MI",
"Carrollton TX",
"Coral Springs FL",
"Midland TX",
"Norman OK",
"Athens-Clarke County GA",
"Santa Clara CA",
"Columbia MO",
"Fargo ND",
"Pearland TX",
"Simi Valley CA",
"Meridian ID",
"Topeka KS",
"Allentown PA",
"Thousand Oaks CA",
"Abilene TX",
"Vallejo CA",
"Concord CA",
"Round Rock TX",
"Arvada CO",
"Clovis CA",
"Palm Bay FL",
"Independence MO",
"Lafayette LA",
"Ann Arbor MI",
"Rochester MN",
"Hartford CT",
"College Station TX",
"Fairfield CA",
"Wilmington NC",
"North Charleston SC",
"Billings MT",
"West Palm Beach FL",
"Berkeley CA",
"Cambridge MA",
"Clearwater FL",
"West Jordan UT",
"Evansville IN",
"Richardson TX",
"Broken Arrow OK",
"Richmond CA",
"League City TX",
"Manchester NH",
"Lakeland FL",
"Carlsbad CA",
"Antioch CA",
"Westminster CO",
"High Point NC",
"Provo UT",
"Lowell MA",
"Elgin IL",
"Waterbury CT",
"Springfield IL",
"Gresham OR",
"Murrieta CA",
"Lewisville TX",
"Las Cruces NM",
"Lansing MI",
"Beaumont TX",
"Odessa TX",
"Pueblo CO",
"Peoria IL",
"Downey CA",
"Pompano Beach FL",
"Miami Gardens FL",
"Temecula CA",
"Everett WA",
"Costa Mesa CA",
"San Buenaventura (Ventura) CA",
"Sparks NV",
"Santa Maria CA",
"Sugar Land TX",
"Greeley CO",
"South Fulton GA",
"Dearborn MI",
"Concord NC",
"Tyler TX",
"Sandy Springs GA",
"West Covina CA",
"Green Bay WI",
"Centennial CO",
"Jurupa Valley CA",
"El Monte CA",
"Allen TX",
"Hillsboro OR",
"Menifee CA",
"Nampa ID",
"Spokane Valley WA",
"Rio Rancho NM",
"Brockton MA",
"El Cajon CA",
"Burbank CA",
"Inglewood CA",
"Renton WA",
"Davie FL",
"Rialto CA",
"Boulder CO",
"South Bend IN",
"Vacaville CA",
"Wichita Falls TX",
"Lee's Summit MO",
"Edinburg TX",
"Chico CA",
"San Mateo CA",
"Bend OR",
"Goodyear AZ",
"Buckeye AZ",
"Daly City CA",
"Fishers IN",
"Quincy MA",
"Davenport IA",
"Hesperia CA",
"New Bedford MA",
"Lynn MA",
"Carmel IN",
"Longmont CO",
"Tuscaloosa AL",
"Norwalk CA",
"St. George UT",
"San Angelo TX",
"Kenosha WI",
"Federal Way WA",
"Roanoke VA",
"New Braunfels TX",
"Vista CA",
"Albany NY",
"Beaverton OR",
"Orem UT",
"Portsmouth VA",
"Yuma AZ",
"Yakima WA",
"Suffolk VA",
"Sunrise FL",
"Boca Raton FL",
"Deltona FL",
"Tracy CA",
"Edmond OK",
"Lawrence KS",
"Fayetteville AR",
"Sandy UT",
"San Marcos CA",
"Reading PA",
"Livonia MI",
"Conroe TX",
"Asheville NC",
"Erie PA",
"Fall River MA",
"Palm Coast FL",
"O'Fallon MO",
"Compton CA",
"Carson CA",
"Redding CA",
"Plantation FL",
"Chino CA",
"Hoover AL",
"Roswell GA",
"Mission Viejo CA",
"Mount Pleasant SC",
"Bellingham WA",
"Fort Myers FL",
"Kirkland WA",
"Norwalk CT",
"South Gate CA",
"Nashua NH",
"Santa Monica CA",
"Lawton OK",
"Avondale AZ",
"Trenton NJ",
"Hemet CA",
"Indio CA",
"Westminster CA",
"Fort Smith AR",
"Clifton NJ",
"Merced CA",
"Bloomington MN",
"Champaign IL",
"San Leandro CA",
"Greenville NC",
"Waukegan IL",
"Lawrence MA",
"Santa Barbara CA",
"Santa Fe NM",
"Springdale AR",
"Newton MA",
"Citrus Heights CA",
"San Ramon CA",
"Bryan TX",
"Troy MI",
"Livermore CA",
"Ogden UT",
"Danbury CT",
"Duluth MN",
"Medford OR",
"Deerfield Beach FL",
"Mission TX",
"Hawthorne CA",
"Manteca CA",
"Lake Forest CA",
"Auburn WA",
"Sioux City IA",
"Franklin TN",
"Temple TX",
"Whittier CA",
"Melbourne FL",
"Newport Beach CA",
"Brooklyn Park MN",
"Westland MI",
"Kennewick WA",
"Farmington Hills MI",
"Layton UT",
"Cicero IL",
"Buena Park CA",
"Warwick RI",
"Cranston RI",
"Baytown TX",
"Largo FL",
"Johns Creek GA",
"Longview TX",
"Redwood City CA",
"New Rochelle NY",
"Mountain View CA",
"Warner Robins GA",
"Folsom CA",
"Alhambra CA",
"Gastonia NC",
"Lake Charles LA",
"Miami Beach FL",
"Flint MI",
"Lakewood CA",
"Homestead FL",
"Rancho Cordova CA",
"South Jordan UT",
"Boynton Beach FL",
"North Port FL",
"Parma OH",
"Lehi UT",
"Bloomington IN",
"Perris CA",
"Plymouth MN",
"Somerville MA",
"Pharr TX",
"Frederick MD",
"Kissimmee FL",
"Tustin CA",
"Jonesboro AR",
"Upland CA",
"Milpitas CA",
"Lynchburg VA",
"Pasco WA",
"Napa CA",
"Cedar Park TX",
"Chino Hills CA",
"Auburn AL",
"Bloomington IL",
"Pleasanton CA",
"Evanston IL",
"Bellflower CA",
"Flower Mound TX",
"Loveland CO",
"Racine WI",
"Schaumburg IL",
"Woodbury MN",
"Flagstaff AZ",
"Hammond IN",
"Wyoming MI",
"Pittsburg CA",
"Alameda CA",
"Redmond WA",
"Castle Rock CO",
"Apple Valley CA",
"Rapid City SD",
"Rochester Hills MI",
"Arlington Heights IL",
"Doral FL",
"Southfield MI",
"Scranton PA",
"Bethlehem PA",
"Georgetown TX",
"Pawtucket RI",
"Broomfield CO",
"Appleton WI",
"Missouri City TX",
"Missoula MT",
"Iowa City IA",
"Daytona Beach FL",
"Mansfield TX",
"Bismarck ND",
"Rock Hill SC",
"New Britain CT",
"Bolingbrook IL",
"Bowling Green KY",
"Lauderhill FL",
"Redlands CA",
"Kalamazoo MI",
"Rocklin CA",
"Jacksonville NC",
"Lakeville MN",
"Turlock CA",
"Mount Vernon NY",
"Gulfport MS",
"Greenville SC",
"Harlingen TX",
"Camden NJ",
"Dublin CA",
"St. Joseph MO",
"Lake Elsinore CA",
"Tamarac FL",
"Eastvale CA",
"Johnson City TN",
"Framingham MA",
"Waukesha WI",
"Dothan AL",
"Marysville WA",
"Rogers AR",
"Blaine MN",
"Noblesville IN",
"Camarillo CA",
"Lafayette IN",
"St. Charles MO",
"Wilmington DE",
"Tulare CA",
"Maple Grove MN",
"Baldwin Park CA",
"Canton OH",
"Ankeny IA",
"North Richland Hills TX",
"West Des Moines IA",
"Redondo Beach CA",
"Walnut Creek CA",
"Decatur IL",
"Passaic NJ",
"Yuba City CA",
"Eau Claire WI",
"Bayonne NJ",
"Gaithersburg MD",
"Albany GA",
"East Orange NJ",
"St. Cloud MN",
"Union City CA",
"Eagan MN",
"San Marcos TX",
"Gary IN",
"Portland ME",
"Jackson TN",
"Yorba Linda CA",
"Madera CA",
"Shawnee KS",
"Haverhill MA",
"Weston FL",
"Rockville MD",
"Leander TX",
"Lodi CA",
"Schenectady NY",
"Grand Junction CO",
"Waterloo IA",
"Idaho Falls ID",
"Pflugerville TX",
"Davis CA",
"Palo Alto CA",
"Sammamish WA",
"Oshkosh WI",
"Delray Beach FL",
"Novi MI",
"Ames IA",
"Skokie IL",
"Queen Creek AZ",
"Palatine IL",
"Alpharetta GA",
"Janesville WI",
"Union City NJ",
"Lynwood CA",
"Lorain OH",
"Victoria TX",
"Kenner LA",
"Muncie IN",
"Conway AR",
"Malden MA",
"Cheyenne WY",
"Greenwood IN",
"Brentwood CA",
"Utica NY",
"Commerce City CO",
"South San Francisco CA",
"Laguna Niguel CA",
"North Little Rock AR",
"Millcreek UT",
"Ocala FL",
"Waltham MA",
"Burnsville MN",
"San Clemente CA",
"Bellevue NE",
"Rowlett TX",
"Caldwell ID",
"Port Orange FL",
"Moore OK",
"Coon Rapids MN",
"Lakewood WA",
"Eden Prairie MN",
"Hamilton OH",
"Apex NC",
"Bossier City LA",
"Porterville CA",
"Maricopa AZ",
"La Habra CA",
"Taylor MI",
"Dearborn Heights MI",
"Council Bluffs IA",
"Hendersonville TN",
"Springfield OR",
"Medford MA",
"St. Cloud FL",
"Santa Cruz CA",
"Richland WA",
"Huntersville NC",
"Encinitas CA",
"Marietta GA",
"Wellington FL",
"Woodland CA",
"Montebello CA",
"Vineland NJ",
"Chapel Hill NC",
"Pontiac MI",
"Jupiter FL",
"San Rafael CA",
"Pico Rivera CA",
"La Mesa CA",
"Sanford FL",
"Bristol CT",
"Meriden CT",
"Euless TX",
"Great Falls MT",
"Parker CO",
"Youngstown OH",
"Owensboro KY",
"Corvallis OR",
"Stonecrest GA",
"Santee CA",
"Gardena CA",
"Kokomo IN",
"Monterey Park CA",
"Taunton MA",
"White Plains NY",
"West Allis WI",
"Des Plaines IL",
"Palm Beach Gardens FL",
"Blue Springs MO",
"Petaluma CA",
"Wylie TX",
"Taylorsville UT",
"North Miami FL",
"Dubuque IA",
"Revere MA",
"Carson City NV",
"Burlington NC",
"Grand Forks ND",
"Springfield OH",
"Hempstead NY",
"Hoboken NJ",
"Casper WY",
"Cupertino CA",
"Terre Haute IN",
"Hanford CA",
"Lenexa KS",
"Madison AL",
"Lake Havasu City AZ",
"St. Clair Shores MI",
"Herriman UT",
"Midwest City OK",
"St. Peters MO",
"Gilroy CA",
"Margate FL",
"Royal Oak MI",
"Shoreline WA",
"Orland Park IL",
"Decatur AL",
"Casa Grande AZ",
"Weymouth Town MA",
"Bowie MD",
"Lancaster PA",
"Kettering OH",
"Bartlett TN",
"Highland CA",
"Coconut Creek FL",
"Pocatello ID",
"Oak Lawn IL",
"Albany OR",
"Bentonville AR",
"Fountain Valley CA",
"Olympia WA",
"National City CA",
"Bradenton FL",
"Coeur d'Alene ID",
"Berwyn IL",
"Tigard OR",
"DeSoto TX",
"Port Arthur TX",
"New Brunswick NJ",
"Smyrna GA",
"Apple Valley MN",
"Kingsport TN",
"Valdosta GA",
"Mount Prospect IL",
"Smyrna TN",
"Apopka FL",
"Southaven MS",
"Brookhaven GA",
"Arcadia CA",
"West Haven CT",
"Perth Amboy NJ",
"San Jacinto CA",
"Beaumont CA",
"Chicopee MA",
"Plainfield NJ",
"Bonita Springs FL",
"Marana AZ",
"Tinley Park IL",
"Anderson IN",
"Sarasota FL",
"Manhattan KS",
"Yucaipa CA",
"Bozeman MT",
"Lacey WA",
"Kannapolis NC",
"Logan UT",
"Colton CA",
"Texas City TX",
"Kentwood MI",
"Peabody MA",
"Rocky Mount NC",
"Elkhart IN",
"Diamond Bar CA",
"Pensacola FL",
"Huntington Park CA",
"West Sacramento CA",
"Normal IL",
"Spring Hill TN",
"Edina MN",
"Minnetonka MN",
"Oak Park IL",
"Galveston TX",
"Twin Falls ID",
"Pinellas Park FL",
"Wheaton IL",
"Elyria OH",
"Methuen MA",
"Winter Haven FL",
"Novato CA",
"Paramount CA",
"Grand Island NE",
"Battle Creek MI",
"West New York NJ",
"Cathedral City CA",
"La Crosse WI",
"Delano CA",
"Watsonville CA",
"Florissant MO",
"Joplin MO",
"Aliso Viejo CA",
"Kyle TX",
"Draper UT",
"Burleson TX",
"Mooresville NC",
"Glendora CA",
"Palm Desert CA",
"Harrisonburg VA",
"Hoffman Estates IL",
"Collierville TN",
"Placentia CA",
"Summerville SC",
"Mishawaka IN",
"Burien WA",
"Little Elm TX",
"Middletown OH",
"Dunwoody GA",
"Grapevine TX",
"Cuyahoga Falls OH",
"Lincoln CA",
"Westfield IN",
"Columbus IN",
"Enid OK",
"Milford CT",
"Covina CA",
"Troy NY",
"Newark OH",
"Jeffersonville IN",
"Rosemead CA",
"Harrisburg PA",
"Lakewood OH",
"Sheboygan WI",
"Cypress CA",
"Eagle Mountain UT",
"Murray UT",
"Chesterfield MO",
"Rockwall TX",
"Wake Forest NC",
"Downers Grove IL",
"Barnstable Town MA",
"Lawrence IN",
"Ceres CA",
"Biloxi MS",
"Bedford TX",
"St. Louis Park MN",
"Dublin OH",
"Euclid OH",
"Leesburg VA",
"Titusville FL",
"Portage MI",
"Azusa CA",
"Everett MA",
"Cedar Hill TX",
"Poway CA",
"Cerritos CA",
"Coral Gables FL",
"Niagara Falls NY",
"Prescott Valley AZ",
"Stillwater OK",
"Roswell NM",
"Charleston WV",
"Cleveland TN",
"Fort Pierce FL",
"Oro Valley AZ",
"Glenview IL",
"Minot ND",
"Bothell WA",
"Wauwatosa WI",
"Wilson NC",
"Mansfield OH",
"Brea CA",
"Binghamton NY",
"San Luis Obispo CA",
"Ocoee FL",
"Rancho Santa Margarita CA",
"Newark CA",
"Monroe LA",
"Mentor OH",
"Roseville MI",
"Middletown CT",
"Hattiesburg MS",
"East Providence RI",
"Gallatin TN",
"East Lansing MI",
"Prescott AZ",
"La Mirada CA",
"Beavercreek OH",
"Attleboro MA",
"Winter Garden FL",
"Salina KS",
"Farmington NM",
"Los Banos CA",
"Huntsville TX",
"Goose Creek SC",
"Strongsville OH",
"Huntington WV",
"Urbandale IA",
"Haltom City TX",
"Charlottesville VA",
"Hackensack NJ",
"Altamonte Springs FL",
"Brentwood TN",
"Sierra Vista AZ",
"Wentzville MO",
"Bountiful UT",
"Plainfield IL",
"Keller TX",
"Morgan Hill CA",
"Elmhurst IL",
"Littleton CO",
"Riverton UT",
"Sayreville NJ",
"Palm Springs CA",
"The Colony TX",
"Blacksburg VA",
"Sherman TX",
"York PA",
"Salem MA",
"Alexandria LA",
"Burlington VT",
"Mankato MN",
"West Lafayette IN",
"Moorhead MN",
"Cleveland Heights OH",
"Fond du Lac WI",
"Fairfield OH",
"Shakopee MN",
"Clermont FL",
"Wilkes-Barre PA",
"Rohnert Park CA",
"Cutler Bay FL",
"North Lauderdale FL",
"Freeport NY",
"Saratoga Springs UT",
"El Centro CA",
"Bremerton WA",
"Concord NH",
"Lombard IL",
"Spanish Fork UT",
"Saginaw MI",
"Lompoc CA",
"Greenacres FL",
"Oakley CA",
"Oakland Park FL",
"Pittsfield MA",
"Leominster MA",
"Linden NJ",
"Hickory NC",
"Altoona PA",
"Holly Springs NC",
"Ormond Beach FL",
"Hagerstown MD",
"Gainesville GA",
"Waxahachie TX",
"Hollister CA",
"Columbia TN",
"Newnan GA",
"Huber Heights OH",
"Danville CA",
"Woonsocket RI",
"Sumter SC",
"Delaware OH",
"Buffalo Grove IL",
"Puyallup WA",
"Jefferson City MO",
"Edmonds WA",
"Campbell CA",
"Manassas VA",
"Schertz TX",
"Post Falls ID",
"Coachella CA",
"North Miami Beach FL",
"Lake Worth Beach FL",
"Midland MI",
"Beverly MA",
"Moline IL",
"San Bruno CA",
"Bullhead City AZ",
"Coppell TX",
"Danville VA",
"Peachtree Corners GA",
"Grove City OH",
"Belleville IL",
"Fitchburg MA",
"Marion IA",
"Shelton CT",
"Brookfield WI",
"Rancho Palos Verdes CA",
"Milton GA",
"Marlborough MA",
"Woburn MA",
"Reynoldsburg OH",
"Germantown TN",
"Weslaco TX",
"Hallandale Beach FL",
"Friendswood TX",
"Indian Trail NC",
"Maplewood MN",
"Lebanon TN",
"Covington KY",
"Mount Juliet TN",
"Lancaster OH",
"Lancaster TX",
"Brighton CO",
"Annapolis MD",
"Lynnwood WA",
"Westfield MA",
"Bartlett IL",
"DeKalb IL",
"Romeoville IL",
"Valley Stream NY",
"Lake Oswego OR",
"Crystal Lake IL",
"Cedar Falls IA",
"New Berlin WI",
"Kearny NJ",
"Olive Branch MS",
"Pine Bluff AR",
"Hurst TX",
"Norwich CT",
"Apache Junction AZ",
"Culver City CA",
"Florence SC",
"Findlay OH",
"Florence AL",
"Cottage Grove MN",
"Fort Lee NJ",
"Cape Girardeau MO",
"Duncanville TX",
"Hobbs NM",
"Hutchinson KS",
"Plant City FL",
"Lincoln Park MI",
"Wausau WI",
"Oviedo FL",
"State College PA",
"Issaquah WA",
"West Fargo ND",
"Rosenberg TX",
"Amherst Town MA",
"Grants Pass OR",
"Roy UT",
"Carol Stream IL",
"Bettendorf IA",
"Aventura FL",
"Keizer OR",
"Quincy IL",
"La Vergne TN",
"Royal Palm Beach FL",
"Warren OH",
"Dover DE",
"Menomonee Falls WI",
"Chelsea MA",
"Greer SC",
"Westerville OH",
"Braintree Town MA",
"Peachtree City GA",
"Park Ridge IL",
"Vestavia Hills AL",
"DeLand FL",
"Owasso OK",
"Urbana IL",
"San Gabriel CA",
"Streamwood IL",
"Bell Gardens CA",
"Calexico CA",
"Wheeling IL",
"Atlantic City NJ",
"Phenix City AL",
"Spartanburg SC",
"Winter Springs FL",
"Prattville AL",
"Portage IN",
"La Quinta CA",
"East Point GA",
"Adelanto CA",
"Hot Springs AR",
"Hilton Head Island SC",
"Riviera Beach FL",
"Montclair CA",
"Clovis NM",
"Stanton CA",
"Pleasant Grove UT",
"Holyoke MA",
"Longview WA",
"Rome GA",
"Georgetown KY",
"Tupelo MS",
"Carpentersville IL",
"Muskegon MI",
"Estero FL",
"Monrovia CA",
"New Albany IN",
"Oregon City OR",
"Bartlesville OK",
"Greenfield WI",
"San Luis AZ",
"Northglenn CO",
"La Puente CA",
"Cedar City UT",
"Wildomar CA",
"Leavenworth KS",
"Tooele UT",
"Myrtle Beach SC",
"Pacifica CA",
"Midlothian TX",
"Copperas Cove TX",
"Hilliard OH",
"Tucker GA",
"Martinez CA",
"Muskogee OK",
"Hanover Park IL",
"Kearns metro township UT",
"Fuquay-Varina NC",
"Rock Island IL",
"Franklin WI",
"Lewiston ME",
"Beloit WI",
"Richfield MN",
"Merrillville IN",
"Farmers Branch TX",
"Upper Arlington OH",
"Lake Stevens WA",
"Oak Creek WI",
"North Ridgeville OH",
"Socorro TX",
"Kiryas Joel NY",
"Woodstock GA",
"Sun Prairie WI",
"Springville UT",
"Texarkana TX",
"El Mirage AZ",
"Moorpark CA",
"La Porte TX",
"Dunedin FL",
"Midvale UT",
"Roseville MN",
"Lima OH",
"Marion OH",
"Norristown PA",
"Richmond IN",
"Windsor CO",
"Temple City CA",
"Salisbury NC",
"Richmond KY",
"Claremont CA",
"Benton AR",
"Lauderdale Lakes FL",
"Plainfield IN",
"Redmond OR",
"San Juan TX",
"Douglasville GA",
"Inver Grove Heights MN",
"Gahanna OH",
"Hinesville GA",
"Wenatchee WA",
"Mount Vernon WA",
"Torrington CT",
"Addison IL",
"Brunswick OH",
"Sahuarita AZ",
"Oswego IL",
"Rexburg ID",
"Parkland FL",
"Wildwood MO",
"Calumet City IL",
"Fair Lawn NJ",
"Watertown Town MA",
"Cookeville TN",
"College Park MD",
"Mason OH",
"San Juan Capistrano CA",
"West Hollywood CA",
"University Place WA",
"Monroe NC",
"Long Beach NY",
"Butte-Silver Bow MT",
"Goshen IN",
"Randolph Town MA",
"Manhattan Beach CA",
"McMinnville OR",
"University City MO",
"Crown Point IN",
"Fairborn OH",
"Northbrook IL",
"Del Rio TX",
"Canton GA",
"Manitowoc WI",
"Lewiston ID",
"Valparaiso IN",
"Meridian MS",
"American Fork UT",
"Stow OH",
"Pleasant Hill CA",
"Dalton GA",
"Prosper TX",
"Lufkin TX",
"San Dimas CA",
"Panama City FL",
"Eastpointe MI",
"Holland MI",
"Westlake OH",
"Cooper City FL",
"Kearney NE",
"Walla Walla WA",
"Woodridge IL",
"Kingman AZ",
"Gadsden AL",
"Leawood KS",
"Weatherford TX",
"Alabaster AL",
"Deer Park TX",
"Harker Heights TX",
"Englewood CO",
"Cibolo TX",
"Petersburg VA",
"Statesboro GA",
"Syracuse UT",
"Dover NH",
"Helena MT",
"Bethel Park PA",
"Kennesaw GA",
"Franklin Town MA",
"Spring Valley NY",
"Sherwood AR",
"Houma LA",
"St. Charles IL",
"Savage MN",
"Kaysville UT",
"Salisbury MD",
"Andover MN",
"Gillette WY",
"Brooklyn Center MN",
"Rochester NH",
"Cottonwood Heights UT",
"Goleta CA",
"Bell CA",
"Pullman WA",
"Dana Point CA",
"Glendale Heights IL",
"Goldsboro NC",
"Wheat Ridge CO",
"Desert Hot Springs CA",
"Fairbanks AK",
"Des Moines WA",
"Los Gatos CA",
"Chester PA",
"Foster City CA",
"Menlo Park CA",
"Garfield NJ",
"Bay City MI",
"Long Branch NJ",
"O'Fallon IL",
"Maryville TN",
"Clearfield UT",
"Massillon OH",
"Bluffton SC",
"Florence KY",
"Nacogdoches TX",
"Eagle ID",
"Seaside CA",
"Elk Grove Village IL",
"Michigan City IN",
"Cleburne TX",
"North Olmsted OH",
"Atwater CA",
"Rome NY",
"Juneau city and AK",
"Garner NC",
"Elizabethtown KY",
"Bangor ME",
"Beverly Hills CA",
"Aiken SC",
"Carlsbad NM",
"Duluth GA",
"Poughkeepsie NY",
"Oak Ridge TN",
"San Pablo CA",
"El Paso de Robles (Paso Robles) CA",
"West Bend WI",
"Ithaca NY",
"Zionsville IN",
"Erie CO",
"Laramie WY",
"Alamogordo NM",
"Cornelius NC",
"Shawnee OK",
"Mundelein IL",
"LaGrange GA",
"Opelika AL",
"Nicholasville KY",
"Dania Beach FL",
"Pekin IL",
"Naugatuck CT",
"Holladay UT",
"Jackson MI",
"New Bern NC",
"Morrisville NC",
"Port Chester NY",
"Newark DE",
"Lawndale CA",
"New Smyrna Beach FL",
"Southlake TX",
"Washington UT",
"Northport AL",
"Lafayette CO",
"North Royalton OH",
"Laguna Hills CA",
"Seguin TX",
"Princeton NJ",
"Ballwin MO",
"Hutto TX",
"North Attleborough Town MA",
"Bella Vista AR",
"Morristown TN",
"Santa Paula CA",
"SeaTac WA",
"Westfield NJ",
"Los Altos CA",
"Hopkinsville KY",
"La Verne CA",
"Sanford NC",
"Bowling Green OH",
"Fitchburg WI",
"Lathrop CA",
"Gurnee IL",
"Lawrenceville GA",
"Middletown NY",
"North Tonawanda NY",
"Miami Lakes FL",
"Liberty MO",
"McDonough GA",
"Niles IL",
"Fridley MN",
"Banning CA",
"Highland Park IL",
"Saratoga CA",
"Burlingame CA",
"Brownsburg IN",
"San Carlos CA",
"North Chicago IL",
"Hazleton PA",
"Central LA",
"Gloucester MA",
"Algonquin IL",
"Rahway NJ",
"Paragould AR",
"Southgate MI",
"Monterey CA",
"Chamblee GA",
"Galesburg IL",
"Atascadero CA",
"Fountain CO",
"Matthews NC",
"Schererville IN",
"Raytown MO",
"Greenville TX",
"Hobart IN",
"Burton MI",
"Laurel MD",
"Parkersburg WV",
"Enterprise AL",
"Kirkwood MO",
"Garfield Heights OH",
"Russellville AR",
"Oak Park MI",
"Texarkana AR",
"Melrose MA",
"Northampton MA",
"Jacksonville AR",
"Anderson SC",
"Magna metro township UT",
"Bixby OK",
"Morgantown WV",
"Suisun City CA",
"Stockbridge GA",
"Winter Park FL",
"Englewood NJ",
"Casselberry FL",
"Haines City FL",
"Sachse TX",
"Shaker Heights OH",
"Lake in the Hills IL",
"Independence KY",
"East Palo Alto CA",
"Statesville NC",
"Newburgh NY",
"Port Huron MI",
"Bridgewater Town MA",
"Burbank IL",
"Danville IL",
"Greenville MS",
"Daphne AL",
"Harrison NY",
"Jeffersontown KY",
"Slidell LA",
"Converse TX",
"West Springfield Town MA",
"Eagle Pass TX",
"Frankfort KY",
"Glen Ellyn IL",
"Agawam Town MA",
"Jamestown NY",
"Lansing IL",
"Fredericksburg VA",
"Monroeville PA",
"Aberdeen SD",
"Rockledge FL",
"Clayton NC",
"Saratoga Springs NY",
"Madison Heights MI",
"Allen Park MI",
"Bergenfield NJ",
"Ramsey MN",
"Marion IN",
"Wasco CA",
"Maple Valley WA",
"Winchester VA",
"Glen Cove NY",
"Ridgecrest CA",
"Prior Lake MN",
"Easton PA",
"Chaska MN",
"Maryland Heights MO",
"Huntley IL",
"Hamtramck MI",
"Fort Mill SC",
"New Iberia LA",
"Oakdale MN",
"Lake Jackson TX",
"Garden City KS",
"West Melbourne FL",
"Walnut CA",
"Crestview FL",
"Leesburg FL",
"Kent OH",
"Madison MS",
"Henderson KY",
"Dodge City KS",
"Mount Pleasant WI",
"Millville NJ",
"New London CT",
"Williamsport PA",
"Wilmette IL",
"Alvin TX",
"Tualatin OR",
"Bristol TN",
"Neenah WI",
"Carrollton GA",
"Granite City IL",
"New Lenox IL",
"Clinton MS",
"Twentynine Palms CA",
"Lemon Grove CA",
"Marshalltown IA",
"Fremont NE",
"McHenry IL",
"Union City GA",
"Green OH",
"Williston ND",
"Ossining NY",
"Lemoore CA",
"Pearl MS",
"Forney TX",
"Belmont CA",
"Thomasville NC",
"Balch Springs TX",
"Lindenhurst NY",
"Mason City IA",
"Asheboro NC",
"West Linn OR",
"Round Lake Beach IL",
"Camas WA",
"Athens AL",
"Gladstone MO",
"Temple Terrace FL",
"Garden City MI",
"South Portland ME",
"Pooler GA",
"Chicago Heights IL",
"Plum PA",
"Benicia CA",
"Oak Forest IL",
"Kernersville NC",
"Vernon Hills IL",
"Palm Springs FL",
"Wooster OH",
"Horn Lake MS",
"Sanger CA",
"Kuna ID",
"Shoreview MN",
"Auburn NY",
"Jenks OK",
"Cabot AR",
"Rosemount MN",
"Mint Hill NC",
"Bridgeton NJ",
"Lebanon PA",
"Wheeling WV",
"Superior WI",
"Brawley CA",
"Key West FL",
"Wilsonville OR",
"Waukee IA",
"Eureka CA",
"Troy OH",
"Oxford MS",
"Paramus NJ",
"Owatonna MN",
"Trussville AL",
"South Pasadena CA",
"Elmira NY",
"Paducah KY",
"Austin MN",
"Marysville OH",
"Florence AZ",
"Ridgewood NJ",
"Elk River MN",
"South Salt Lake UT",
"Lockport IL",
"Kalispell MT",
"East Chicago IN",
"Batavia IL",
"Hercules CA",
"Forest Grove OR",
"Norco CA",
"Imperial Beach CA",
"Woodburn OR",
"Homewood AL",
"Venice FL",
"Windsor CA",
"Chanhassen MN",
"Colleyville TX",
"Leland NC",
"Lodi NJ",
"Winona MN",
"Medina OH",
"Moscow ID",
"Derby KS",
"El Cerrito CA",
"Grandview MO",
"Tumwater WA",
"Rockville Centre NY",
"Peekskill NY",
"Big Spring TX",
"Inkster MI",
"Sebastian FL",
"Stevens Point WI",
"Happy Valley OR",
"Staunton VA",
"Mauldin SC",
"Woodstock IL",
"Bessemer AL",
"Cliffside Park NJ",
"Avon Lake OH",
"Moses Lake WA",
"Tarpon Springs FL",
"Galt CA",
"Newberg OR",
"Xenia OH",
"Mercer Island WA",
"Barstow CA",
"Franklin IN",
"Alton IL",
"Salem VA",
"Brandon MS",
"West Chicago IL",
"Ottumwa IA",
"De Pere WI",
"Avon OH",
"Sugar Hill GA",
"Muskego WI",
"Hazelwood MO",
"Reedley CA",
"Caledonia WI",
"Edwardsville IL",
"Lafayette CA",
"Corsicana TX",
"Mequon WI",
"Norton Shores MI",
"Denison TX",
"Fulshear TX",
"Dickinson ND",
"Newport RI",
"Walker MI",
"Carteret NJ",
"Dinuba CA",
"Belvidere IL",
"Perrysburg OH",
"Romulus MI",
"Loma Linda CA",
"Kingsville TX",
"Hastings NE",
"Barberton OH",
"Norfolk NE",
"Seal Beach CA",
"Fort Dodge IA",
"Ardmore OK",
"University Park TX",
"Riverbank CA",
"San Benito TX",
"Soledad CA",
"Farmington UT",
"Sandusky OH",
"Centerville OH",
"Zanesville OH",
"Morton Grove IL",
"Oak Harbor WA",
"Pelham AL",
"Auburn Hills MI",
"Simpsonville SC",
"Wyandotte MI",
"North Augusta SC",
"Starkville MS",
"Selma CA",
"Yukon OK",
"Benbrook TX",
"Watertown NY",
"Decatur GA",
"Maywood CA",
"Greenbelt MD",
"Bainbridge Island WA",
"Homer Glen IL",
"Zion IL",
"Kerrville TX",
"Mandan ND",
"Clinton IA",
"Farragut TN",
"Faribault MN",
"Paris TX",
"Ponca City OK",
"Riverside OH",
"Herndon VA",
"Collinsville IL",
"Athens OH",
"Fairfax VA",
"Wadsworth OH",
"South Plainfield NJ",
"Lexington SC",
"Melrose Park IL",
"Belton MO",
"Johnston IA",
"Raymore MO",
"Middletown DE",
"West Memphis AR",
"Westmont IL",
"Nixa MO",
"White Bear Lake MN",
"Columbus NE",
"Papillion NE",
"Kingston NY",
"Ridgeland MS",
"Auburn ME",
"Saginaw TX",
"Greenfield IN",
"Emporia KS",
"Katy TX",
"Pickerington OH",
"Elmwood Park IL",
"Gardner KS",
"Solon OH",
"Kankakee IL",
"South Elgin IL",
"Willoughby OH",
"Lisle IL",
"Belton TX",
"Roseburg OR",
"Palmetto Bay FL",
"Fountain Hills AZ",
"Celina TX",
"Patterson CA",
"Rolling Meadows IL",
"Webster Groves MO",
"Munster IN",
"Shelbyville TN",
"San Fernando CA",
"Burlington IA",
"Highland IN",
"Freeport IL",
"Griffin GA",
"Clinton UT",
"Brookings SD",
"Eustis FL",
"Farmington MN",
"Jacksonville Beach FL",
"Fernley NV",
"Kenmore WA",
"Champlin MN",
"Muscatine IA",
"Easley SC",
"Pottstown PA",
"Van Buren AR",
"Maple Heights OH",
"Columbus MS",
"Watauga TX",
"Loves Park IL",
"Edgewater FL",
"Oakdale CA",
"Cartersville GA",
"Rock Springs WY",
"Horizon City TX",
"Fairhope AL",
"Hopewell VA",
"Conway SC",
"Maywood IL",
"Keene NH",
"Searcy AR",
"Garden City NY",
"Hudson OH",
"North Platte NE",
"Trotwood OH",
"Coralville IA",
"Radcliff KY",
"Calabasas CA",
"New Brighton MN",
"Watertown WI",
"Prairie Village KS",
"Avon IN",
"Bonney Lake WA",
"Laguna Beach CA",
"Duncan OK",
"Watertown SD",
"Crystal MN",
"Machesney Park IL",
"Corinth TX",
"Marshall TX",
"Roselle IL",
"Middleton WI",
"DeBary FL",
"Oxford OH",
"Christiansburg VA",
"Yorkville IL",
"Biddeford ME",
"Waynesboro VA",
"Corcoran CA",
"Summit NJ",
"Albertville AL",
"Hialeah Gardens FL",
"Marina CA",
"North Plainfield NJ",
"Central Falls RI",
"Roselle NJ",
"Junction City KS",
"Bloomingdale IL",
"La Porte IN",
"Chambersburg PA",
"Oxford AL",
"North Salt Lake UT",
"Evans CO",
"Cudahy CA",
"Acworth GA",
"Ruston LA",
"Portsmouth NH",
"Millbrae CA",
"East Peoria IL",
"Greenwood SC",
"Sapulpa OK",
"Mountain Brook AL",
"Payson UT",
"Sanford ME",
"Clarksville IN",
"Sunny Isles Beach FL",
"Foley AL",
"Klamath Falls OR",
"Perry GA",
"Chillicothe OH",
"Blue Island IL",
"Villa Park IL",
"East Ridge TN",
"Shelby NC",
"Golden Valley MN",
"Hastings MN",
"Suwanee GA",
"Ozark MO",
"Pascagoula MS",
"Columbia Heights MN",
"Yucca Valley CA",
"Sedalia MO",
"Hurricane UT",
"Alliance OH",
"Birmingham MI",
"Darien IL",
"New Castle PA",
"Carbondale IL",
"Port Hueneme CA",
"Dickinson TX",
"Waxhaw NC",
"Tukwila WA",
"Lino Lakes MN",
"South Euclid OH",
"Ashland OR",
"American Canyon CA",
"Del City OK",
"Helena AL",
"Lindenwold NJ",
"North Ogden UT",
"Clemmons NC",
"Rocky River OH",
"Gallup NM",
"Seymour IN",
"Hanahan SC",
"Ashland KY",
"St. John IN",
"Mineola NY",
"Mountlake Terrace WA",
"South Lake Tahoe CA",
"Otsego MN",
"Pleasant Prairie WI",
"New Hope MN",
"Carrboro NC",
"Montgomery IL",
"Secaucus NJ",
"Elmwood Park NJ",
"Park Forest IL",
"Geneva IL",
"Mukilteo WA",
"Duarte CA",
"Mount Pleasant MI",
"Murphy TX",
"Ennis TX",
"Stephenville TX",
"Baldwin PA",
"Lebanon OH",
"Gardner MA",
"Mesquite NV",
"Anniston AL",
"East Moline IL",
"Grayslake IL",
"Battle Ground WA",
"Bryant AR",
"Willmar MN",
"Mustang OK",
"Imperial CA",
"South Holland IL",
"Fate TX",
"Louisville CO",
"Milwaukie OR",
"Dolton IL",
"Germantown WI",
"Vicksburg MS",
"Mill Creek WA",
"Fort Walton Beach FL",
"North Liberty IA",
"Hyattsville MD",
"Murrysville PA",
"West St. Paul MN",
"Arnold MO",
"Hays KS",
"Covington WA",
"Glassboro NJ",
"Snellville GA",
"Lockport NY",
"Pittsburg KS",
"Northfield MN",
"Altoona IA",
"Shafter CA",
"Saco ME",
"Tullahoma TN",
"Montrose CO",
"Sulphur LA",
"Elko NV",
"Forest Lake MN",
"Pleasantville NJ",
"Painesville OH",
"Westbrook ME",
"Parma Heights OH",
"South St. Paul MN",
"Portland TX",
"South Milwaukee WI",
"Bethany OK",
"Adrian MI",
"Libertyville IL",
"Culpeper VA",
"Frankfort IL",
"Piqua OH",
"Lomita CA",
"Sidney OH",
"Groveland FL",
"Marquette MI",
"Monroe MI",
"Lynbrook NY",
"Crest Hill IL",
"South Burlington VT",
"Morristown NJ",
"Sherwood OR",
"Anna TX",
"Howard WI",
"Monroe WA",
"Palisades Park NJ",
"Carlisle PA",
"Port Angeles WA",
"Rolla MO",
"La Cañada Flintridge CA",
"Ypsilanti MI",
"Whitehall OH",
"Arlington WA",
"Westminster MD",
"Shelbyville IN",
"Princeton TX",
"Mayfield Heights OH",
"Alamo TX",
"Zachary LA",
"Brigham City UT",
"Centerton AR",
"Punta Gorda FL",
"Hammond LA",
"Sand Springs OK",
"Forest Park OH",
"Plattsburgh NY",
"Oroville CA",
"West Haven UT",
"Mamaroneck NY",
"Harvey IL",
"Golden CO",
"Oregon OH",
"Coronado CA",
"Mokena IL",
"Agoura Hills CA",
"Universal City TX",
"Lackawanna NY",
"Forest Park GA",
"Miamisburg OH",
"Nogales AZ",
"Plainview TX",
"Erlanger KY",
"Broadview Heights OH",
"Arvin CA",
"Lake Zurich IL",
"Liberal KS",
"Warrensburg MO",
"Highland UT",
"Ellensburg WA",
"South El Monte CA"]}
def get_cities(value):
    return country_code_to_cities[value]
